#!/bin/sh
set -e

# Install AFL
wget http://lcamtuf.coredump.cx/afl/releases/afl-latest.tgz \
    && tar -xzvf afl-latest.tgz \
    && rm -rf afl-latest.tgz \
    && cd afl-2.52b/ \
    && make \
    && sudo make install

# Install Honggfuzz
git clone https://github.com/google/honggfuzz \
    && cd honggfuzz \
    && make \
    && sudo make install

# Install Eclipser
git clone https://github.com/SoftSec-KAIST/Eclipser \
    && cd Eclipser \
    && make

# Install Angora
git clone https://github.com/AngoraFuzzer/Angora \
    && cd Angora \
    && ./build/build.sh

# Build and install DeepState under a variety of compilers
cd deepstate \
    && rm -Rf CMakeFiles CMakeCache.txt \
    && rm -Rf build \
    && mkdir -p build \
    && cd build \

    && rm -rf CMakeFiles CMakeCache.txt \
    && CXX=clang++ CC=clang cmake -DDEEPSTATE_LIBFUZZER=ON ../ \
    && sudo make install \
    \
    && rm -rf CMakeFiles CMakeCache.txt \
    && CXX=afl-clang++ CC=afl-clang cmake -DDEEPSTATE_AFL=ON ../ \
    && sudo make install \
    \
    && rm -rf CMakeFiles CMakeCache.txt \
    && CXX=hfuzz-clang++ CC=hfuzz-clang cmake -DDEEPSTATE_HFUZZ=ON ../ \
    && sudo make install \
    \
    && rm -rf CMakeFiles CMakeCache.txt \
    && export USE_TRACK=1 \
    && CXX=$ANGORA/bin/angora-clang++ CC=$ANGORA/bin/angora-clang cmake -DDEEPSTATE_ANGORA=ON ../ \
    && sudo make -i install \
    && make clean \
    && rm -rf CMakeFiles CMakeCache.txt \
    && unset USE_TRACK && export USE_FAST=1 \
    && CXX=$ANGORA/bin/angora-clang++ CC=$ANGORA/bin/angora-clang cmake -DDEEPSTATE_ANGORA=ON ../ \
    && sudo make install \
    \
    && cd .. \
    && pip3 install 'z3-solver==4.5.1.0.post2' angr git+git://github.com/trailofbits/manticore.git --user \
    && python3 ./build/setup.py install
